# Generated by Django 5.0.2 on 2024-12-08 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_rename_price_event_total_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='total_price',
            new_name='price',
        ),
    ]
