# Generated by Django 5.0.2 on 2024-12-15 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_rename_total_price_event_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='price',
        ),
    ]
